-- Clear existing trek data and insert comprehensive trek list
DELETE FROM treks;

-- Insert all the requested treks with detailed information
INSERT INTO treks (title, description, image_url, duration, difficulty, price, overview, highlights, who_can_participate, itinerary, how_to_reach, cost_terms, trek_essentials) VALUES

-- Himalayan Treks
('Adi Kailash and Om Parvat', 'Sacred pilgrimage trek to the mystical Adi Kailash and Om Parvat in the remote Himalayas.', '/placeholder.svg?height=300&width=400', '12 Days', 'Moderate to Difficult', 45000.00, 'A spiritual journey to two of the most sacred peaks in the Himalayas, offering breathtaking views and cultural immersion.', ARRAY['Sacred pilgrimage sites', 'Remote Himalayan wilderness', 'Cultural experiences', 'Stunning mountain vistas'], 'Suitable for trekkers with good physical fitness and previous high-altitude experience.', '{"day1": "Arrival in Dharchula", "day2": "Drive to Gunji", "day3": "Acclimatization day", "day4": "Trek to Adi Kailash base"}'::jsonb, 'Fly to Delhi, drive to Dharchula via Pithoragarh. Detailed itinerary provided upon booking.', 'Full payment 45 days before trek. Medical certificate mandatory. High altitude insurance required.', ARRAY['High-altitude gear', 'Warm clothing', 'Trekking boots', 'Personal medications', 'Sleeping bag']),

('Ali Bedni Bugyal Trek', 'Explore the pristine alpine meadows of Ali and Bedni Bugyal with panoramic Himalayan views.', '/placeholder.svg?height=300&width=400', '6 Days', 'Easy to Moderate', 12000.00, 'Trek through lush green meadows and dense forests to reach some of the most beautiful bugyals in Uttarakhand.', ARRAY['Vast alpine meadows', 'Panoramic mountain views', 'Rich flora and fauna', 'Photography paradise'], 'Perfect for beginners and nature lovers. Basic fitness level required.', '{"day1": "Lohajung to Didina", "day2": "Didina to Ali Bugyal", "day3": "Ali to Bedni Bugyal", "day4": "Explore and return"}'::jsonb, 'Drive from Kathgodam to Lohajung. Transportation can be arranged from Delhi.', 'Advance booking required. Weather dependent cancellation policy applies.', ARRAY['Trekking shoes', 'Warm clothes', 'Rain gear', 'Backpack', 'Water bottles']),

('Annapurna Base Camp Trek', 'Classic Nepal trek to the base camp of the mighty Annapurna massif through diverse landscapes.', '/placeholder.svg?height=300&width=400', '12 Days', 'Moderate', 35000.00, 'Journey through rhododendron forests, traditional villages, and terraced fields to reach Annapurna Base Camp at 4,130m.', ARRAY['Annapurna massif views', 'Cultural diversity', 'Hot springs at Jhinu', 'Sunrise at base camp'], 'Suitable for trekkers with moderate fitness levels and some trekking experience.', '{"day1": "Fly to Pokhara", "day2": "Drive to Nayapul, trek to Tikhedhunga", "day3": "Trek to Ghorepani", "day4": "Poon Hill sunrise, trek to Tadapani"}'::jsonb, 'Fly to Kathmandu, then to Pokhara. Trek starts from Nayapul.', 'Nepal visa required. Full payment 30 days before. Travel insurance mandatory.', ARRAY['Trekking boots', 'Layered clothing', 'Sleeping bag', 'Trekking poles', 'Headlamp']),

('Annapurna Circuit Trek', 'Complete circuit around the Annapurna massif crossing the challenging Thorong La Pass.', '/placeholder.svg?height=300&width=400', '16 Days', 'Moderate to Difficult', 42000.00, 'One of the worlds classic treks, offering incredible diversity of landscapes, cultures, and the challenge of Thorong La Pass at 5,416m.', ARRAY['Thorong La Pass crossing', 'Diverse ecosystems', 'Ancient trade routes', 'Muktinath temple visit'], 'For experienced trekkers with excellent fitness. Previous high-altitude experience recommended.', '{"day1": "Drive to Besisahar", "day2": "Trek to Bahundanda", "day3": "Trek to Chamje", "day4": "Trek to Dharapani"}'::jsonb, 'Fly to Kathmandu, drive to Besisahar or fly to Pokhara then drive.', 'Nepal visa and permits required. Comprehensive travel insurance mandatory.', ARRAY['Four-season sleeping bag', 'High-altitude clothing', 'Trekking boots', 'Crampons', 'Emergency supplies']),

-- Indian Himalayan Treks
('Brahmatal Trek', 'Winter wonderland trek to the frozen Brahmatal lake with stunning views of Trishul and Nanda Ghunti.', '/placeholder.svg?height=300&width=400', '6 Days', 'Easy to Moderate', 8500.00, 'Perfect winter trek through snow-covered forests leading to the beautiful Brahmatal lake surrounded by towering peaks.', ARRAY['Frozen lake views', 'Snow trekking', 'Oak and rhododendron forests', '360-degree mountain panorama'], 'Ideal for beginners wanting to experience snow trekking. Good fitness level required.', '{"day1": "Lohajung to Bekaltal", "day2": "Bekaltal to Brahmatal", "day3": "Brahmatal summit and return", "day4": "Descent to Lohajung"}'::jsonb, 'Drive from Kathgodam to Lohajung. Regular buses available from Delhi to Kathgodam.', 'Winter trek. Weather dependent. Full payment 15 days before trek.', ARRAY['Snow boots', 'Gaiters', 'Warm layers', 'Gloves', 'Snow goggles']),

('Kedarkantha Trek', 'Popular winter summit trek offering panoramic views of major Himalayan peaks.', '/placeholder.svg?height=300&width=400', '5 Days', 'Easy to Moderate', 7500.00, 'Climb to 3,800m summit through pine forests and snow-covered meadows with spectacular 360-degree mountain views.', ARRAY['Summit climb experience', 'Snow camping', 'Panoramic Himalayan views', 'Pine forest trails'], 'Perfect for beginners and families. Suitable for first-time trekkers.', '{"day1": "Sankri to Juda ka Talab", "day2": "Juda ka Talab to Kedarkantha Base", "day3": "Summit day and return", "day4": "Descent to Sankri"}'::jsonb, 'Drive from Dehradun to Sankri. Taxi services available from Dehradun railway station.', 'Popular winter trek. Early booking recommended. Weather cancellation policy applies.', ARRAY['Trekking boots', 'Warm clothing', 'Sleeping bag', 'Trekking poles', 'Headlamp']),

('Roopkund Trek', 'Mystery lake trek famous for ancient human skeletons and challenging high-altitude terrain.', '/placeholder.svg?height=300&width=400', '8 Days', 'Difficult', 18000.00, 'Discover the mysterious skeleton lake at 5,020m altitude, passing through beautiful bugyals and challenging mountain terrain.', ARRAY['Mystery skeleton lake', 'High altitude challenge', 'Ali and Bedni Bugyal', 'Junargali ridge views'], 'For experienced trekkers only. Excellent physical fitness and previous high-altitude experience essential.', '{"day1": "Lohajung to Didina", "day2": "Didina to Ali Bugyal", "day3": "Ali to Bedni Bugyal", "day4": "Bedni to Roopkund"}'::jsonb, 'Drive from Kathgodam to Lohajung. Pre-trek medical checkup mandatory.', 'Medical certificate required. High-altitude insurance mandatory. No refund after trek commencement.', ARRAY['High-altitude gear', 'Microspikes', 'Gaiters', 'Insulated jacket', 'Emergency equipment']),

('Valley of Flowers Trek', 'UNESCO World Heritage site famous for its endemic alpine flowers and natural beauty.', '/placeholder.svg?height=300&width=400', '6 Days', 'Easy to Moderate', 12000.00, 'Trek through the enchanting valley filled with hundreds of wildflower species and stunning mountain backdrop.', ARRAY['UNESCO World Heritage site', 'Diverse alpine flora', 'Hemkund Sahib visit', 'Photography opportunities'], 'Suitable for nature lovers and photographers. Moderate fitness required.', '{"day1": "Haridwar to Govindghat", "day2": "Govindghat to Ghangaria", "day3": "Valley of Flowers exploration", "day4": "Hemkund Sahib visit"}'::jsonb, 'Drive from Haridwar to Govindghat. Regular bus services available.', 'Seasonal trek (July-September). Advance booking essential. Weather dependent.', ARRAY['Comfortable trekking shoes', 'Rain protection', 'Camera equipment', 'Light backpack', 'Personal medications']),

-- Ladakh Treks
('Chadar Trek Frozen River', 'Walk on the frozen Zanskar River in the heart of Ladakh winter.', '/placeholder.svg?height=300&width=400', '9 Days', 'Difficult', 25000.00, 'Unique winter trek walking on the frozen Zanskar River through dramatic gorges in sub-zero temperatures.', ARRAY['Frozen river walking', 'Extreme winter conditions', 'Zanskari culture', 'Ice formations'], 'Only for experienced trekkers with excellent cold weather tolerance. Previous winter trekking experience essential.', '{"day1": "Leh acclimatization", "day2": "Leh to Chilling", "day3": "Start Chadar trek", "day4": "Trek on frozen river"}'::jsonb, 'Fly to Leh. Mandatory acclimatization days required before trek.', 'Extreme weather trek. Comprehensive insurance mandatory. Medical clearance required.', ARRAY['Extreme cold weather gear', 'Insulated boots', 'Sleeping system rated -20°C', 'Emergency equipment', 'High-energy food']),

('Markha Valley Trek', 'Classic Ladakh trek through traditional villages and high-altitude desert landscapes.', '/placeholder.svg?height=300&width=400', '7 Days', 'Moderate', 22000.00, 'Trek through the beautiful Markha Valley visiting traditional Ladakhi villages and crossing high mountain passes.', ARRAY['Traditional Ladakhi culture', 'High-altitude desert', 'Kongmaru La pass', 'Wildlife spotting'], 'Suitable for trekkers with good fitness and some high-altitude experience.', '{"day1": "Leh to Spituk", "day2": "Spituk to Rumbak", "day3": "Rumbak to Yurutse", "day4": "Yurutse to Shang Sumdo"}'::jsonb, 'Fly to Leh. Acclimatization days mandatory before starting trek.', 'High-altitude trek. Permits required. Weather dependent cancellation policy.', ARRAY['High-altitude clothing', 'Sun protection', 'Trekking boots', 'Sleeping bag', 'Water purification']),

('Stok Kangri Peak Trek Expedition', 'Climb the highest trekkable peak in the Stok range at 6,153m altitude.', '/placeholder.svg?height=300&width=400', '10 Days', 'Very Difficult', 35000.00, 'Technical climb to one of Ladakhs highest peaks offering spectacular views of the Karakoram and Himalayan ranges.', ARRAY['6000m+ peak climbing', 'Technical mountaineering', 'Panoramic Ladakh views', 'Mountaineering skills development'], 'Only for experienced mountaineers with previous high-altitude climbing experience.', '{"day1": "Leh acclimatization", "day2": "Stok village to base camp", "day3": "Acclimatization climbs", "day4": "Summit attempt"}'::jsonb, 'Fly to Leh. Extended acclimatization period mandatory.', 'Mountaineering experience required. Comprehensive insurance mandatory. Equipment rental available.', ARRAY['Mountaineering equipment', 'High-altitude boots', 'Climbing gear', 'Emergency equipment', 'Technical clothing']),

-- Kashmir Treks
('Kashmir Great Lakes Trek', 'Trek through multiple pristine alpine lakes in the Kashmir Himalayas.', '/placeholder.svg?height=300&width=400', '8 Days', 'Moderate to Difficult', 16000.00, 'Spectacular trek visiting seven beautiful alpine lakes surrounded by snow-capped peaks and colorful meadows.', ARRAY['Seven pristine lakes', 'Alpine meadows', 'Gangabal and Nundkol lakes', 'Diverse landscapes'], 'For trekkers with good fitness and some mountain experience. Weather dependent.', '{"day1": "Srinagar to Sonamarg", "day2": "Sonamarg to Nichnai", "day3": "Nichnai to Vishansar Lake", "day4": "Vishansar to Gadsar"}'::jsonb, 'Fly to Srinagar. Drive to Sonamarg to start trek.', 'Seasonal trek. Security clearance may be required. Weather dependent cancellation.', ARRAY['Trekking boots', 'Warm layers', 'Rain gear', 'Sleeping bag', 'Trekking poles']),

('Tarsar Marsar Trek', 'Twin lake trek in Kashmir offering pristine alpine beauty and solitude.', '/placeholder.svg?height=300&width=400', '6 Days', 'Moderate', 14000.00, 'Visit two stunning alpine lakes connected by a beautiful valley with excellent camping spots and mountain views.', ARRAY['Twin alpine lakes', 'Pristine wilderness', 'Excellent camping', 'Photography opportunities'], 'Suitable for intermediate trekkers with moderate fitness levels.', '{"day1": "Srinagar to Aru", "day2": "Aru to Lidderwat", "day3": "Lidderwat to Shekwas", "day4": "Shekwas to Tarsar Lake"}'::jsonb, 'Fly to Srinagar, drive to Aru valley via Pahalgam.', 'Seasonal availability. Permits may be required. Weather dependent operations.', ARRAY['Trekking equipment', 'Warm clothing', 'Camping gear', 'Photography equipment', 'Personal supplies']),

-- Himachal Pradesh Treks
('Hampta Pass Trek', 'Cross from Kullu to Lahaul valley through the scenic Hampta Pass.', '/placeholder.svg?height=300&width=400', '5 Days', 'Easy to Moderate', 9500.00, 'Beautiful trek crossing from green Kullu valley to the barren landscapes of Lahaul Spiti through Hampta Pass.', ARRAY['Valley transition experience', 'Chandratal Lake visit', 'Diverse landscapes', 'Accessible for beginners'], 'Perfect for beginners and families. Good introduction to Himalayan trekking.', '{"day1": "Manali to Jobra to Chika", "day2": "Chika to Balu ka Ghera", "day3": "Hampta Pass to Shea Goru", "day4": "Chandratal Lake visit"}'::jsonb, 'Drive from Delhi to Manali. Trek starts from Jobra near Manali.', 'Popular summer trek. Early booking recommended. Weather dependent.', ARRAY['Trekking shoes', 'Layered clothing', 'Rain protection', 'Backpack', 'Personal items']),

('Beas Kund Trek', 'Short trek to the source of river Beas with stunning mountain views.', '/placeholder.svg?height=300&width=400', '4 Days', 'Easy', 6500.00, 'Easy trek to the glacial lake that is the source of river Beas, surrounded by towering peaks.', ARRAY['Source of river Beas', 'Glacial lake', 'Mountain panorama', 'Short duration'], 'Ideal for beginners and weekend trekkers. Family-friendly trek.', '{"day1": "Manali to Solang to Dhundi", "day2": "Dhundi to Bakarthach", "day3": "Bakarthach to Beas Kund", "day4": "Return to Manali"}'::jsonb, 'Drive from Delhi to Manali. Trek starts from Solang Valley.', 'Year-round trek. Weather dependent in winter. Easy cancellation policy.', ARRAY['Basic trekking gear', 'Comfortable shoes', 'Warm clothes', 'Day pack', 'Water bottles']),

('Bhrigu Lake Trek', 'High-altitude lake trek near Manali offering panoramic mountain views.', '/placeholder.svg?height=300&width=400', '3 Days', 'Easy to Moderate', 5500.00, 'Trek to the sacred Bhrigu Lake at 4,300m altitude with spectacular views of Pir Panjal ranges.', ARRAY['High-altitude lake', 'Panoramic views', 'Sacred significance', 'Weekend trek'], 'Suitable for weekend warriors and beginners wanting high-altitude experience.', '{"day1": "Manali to Gulaba to Rola Kholi", "day2": "Rola Kholi to Bhrigu Lake", "day3": "Return to Manali"}'::jsonb, 'Drive from Delhi to Manali. Trek starts from Gulaba.', 'Short trek ideal for weekends. Weather dependent availability.', ARRAY['Trekking boots', 'Warm layers', 'Rain gear', 'Day pack', 'Sun protection']),

-- Uttarakhand Treks
('Har Ki Dun Trek', 'Valley of Gods trek through ancient villages and pristine Himalayan wilderness.', '/placeholder.svg?height=300&width=400', '7 Days', 'Easy to Moderate', 11000.00, 'Trek through the hanging valley known as Valley of Gods with rich biodiversity and cultural heritage.', ARRAY['Valley of Gods', 'Ancient villages', 'Rich biodiversity', 'Cultural immersion'], 'Perfect for nature lovers and cultural enthusiasts. Moderate fitness required.', '{"day1": "Dehradun to Sankri", "day2": "Sankri to Taluka to Osla", "day3": "Osla to Har Ki Dun", "day4": "Explore and return"}'::jsonb, 'Drive from Dehradun to Sankri. Regular transport available.', 'Year-round trek with seasonal variations. Advance booking recommended.', ARRAY['Trekking boots', 'Layered clothing', 'Rain protection', 'Backpack', 'Camera']),

('Dayara Bugyal Trek', 'Beautiful meadow trek offering stunning views of Bandarpoonch and other peaks.', '/placeholder.svg?height=300&width=400', '4 Days', 'Easy', 7000.00, 'Trek through vast alpine meadows with panoramic views of major Himalayan peaks and excellent camping.', ARRAY['Vast meadows', 'Panoramic mountain views', 'Easy accessibility', 'Great for beginners'], 'Ideal for beginners and families. Easy trek with beautiful rewards.', '{"day1": "Dehradun to Barsu", "day2": "Barsu to Dayara Bugyal", "day3": "Explore meadows", "day4": "Return to Dehradun"}'::jsonb, 'Drive from Dehradun to Barsu village. Good road connectivity.', 'Year-round accessibility. Winter offers snow experience.', ARRAY['Basic trekking gear', 'Comfortable shoes', 'Warm clothes', 'Camping equipment', 'Personal items']),

-- International Treks
('Everest Base Camp Trek', 'Iconic trek to the base camp of the worlds highest mountain.', '/placeholder.svg?height=300&width=400', '14 Days', 'Difficult', 65000.00, 'Classic trek to Everest Base Camp through Sherpa villages, monasteries, and stunning Himalayan landscapes.', ARRAY['Everest Base Camp', 'Sherpa culture', 'Sagarmatha National Park', 'Kala Patthar viewpoint'], 'For experienced trekkers with excellent fitness and previous high-altitude experience.', '{"day1": "Fly to Lukla", "day2": "Lukla to Namche Bazaar", "day3": "Acclimatization in Namche", "day4": "Namche to Tengboche"}'::jsonb, 'Fly to Kathmandu, then to Lukla. Weather dependent flights.', 'Nepal visa and permits required. Comprehensive insurance mandatory. Weather dependent.', ARRAY['High-altitude gear', 'Four-season sleeping bag', 'Trekking boots', 'Layered clothing', 'Emergency supplies']),

('Mount Kilimanjaro Trek', 'Climb Africas highest peak and the worlds tallest free-standing mountain.', '/placeholder.svg?height=300&width=400', '7 Days', 'Difficult', 85000.00, 'Climb to the roof of Africa through diverse climate zones from tropical to arctic conditions.', ARRAY['Highest peak in Africa', 'Diverse climate zones', 'Uhuru Peak summit', 'Unique wildlife'], 'For experienced trekkers with excellent physical fitness and mental determination.', '{"day1": "Machame Gate to Machame Camp", "day2": "Machame to Shira Camp", "day3": "Shira to Barranco", "day4": "Barranco to Karanga"}'::jsonb, 'Fly to Kilimanjaro International Airport. Transfers to Machame Gate included.', 'Tanzania visa required. Yellow fever vaccination mandatory. Comprehensive travel insurance required.', ARRAY['High-altitude clothing', 'Four-season gear', 'Trekking boots', 'Sleeping system', 'Personal medications']),

-- Peak Expeditions
('Friendship Peak Expedition', 'Technical climbing expedition to 5,289m peak in Pir Panjal range.', '/placeholder.svg?height=300&width=400', '12 Days', 'Very Difficult', 28000.00, 'Mountaineering expedition combining trekking and technical climbing skills to reach Friendship Peak summit.', ARRAY['Technical mountaineering', 'Rope and ice climbing', 'High-altitude camping', 'Mountaineering certification'], 'Only for experienced climbers with previous mountaineering experience and technical skills.', '{"day1": "Manali to Solang", "day2": "Solang to Dhundi", "day3": "Dhundi to Beas Kund", "day4": "Establish higher camps"}'::jsonb, 'Drive from Delhi to Manali. Technical briefing and equipment check mandatory.', 'Mountaineering course certificate required. Equipment rental available. Weather dependent.', ARRAY['Mountaineering equipment', 'Technical climbing gear', 'High-altitude clothing', 'Safety equipment', 'Personal climbing gear']),

-- Specialty Treks
('Yoga & Meditation Retreat In The Himalayas', 'Combine trekking with yoga and meditation in serene Himalayan settings.', '/placeholder.svg?height=300&width=400', '7 Days', 'Easy', 15000.00, 'Rejuvenating experience combining gentle trekking with daily yoga sessions and meditation in pristine mountain environment.', ARRAY['Daily yoga sessions', 'Meditation practices', 'Himalayan serenity', 'Wellness focus'], 'Suitable for all levels. Focus on wellness and spiritual growth rather than physical challenge.', '{"day1": "Arrival and orientation", "day2": "Gentle trek with yoga", "day3": "Meditation and nature walks", "day4": "Advanced practices"}'::jsonb, 'Peaceful location accessible by road. Detailed location provided upon booking.', 'All-inclusive retreat. Vegetarian meals provided. Suitable for beginners.', ARRAY['Comfortable clothes', 'Yoga mat', 'Meditation cushion', 'Light trekking shoes', 'Personal items']),

('Leh Ladakh Multi-Sports Trip', 'Adventure sports combination including trekking, cycling, and river rafting in Ladakh.', '/placeholder.svg?height=300&width=400', '10 Days', 'Moderate to Difficult', 32000.00, 'Multi-activity adventure including trekking, mountain biking, river rafting, and cultural exploration in Ladakh.', ARRAY['Multiple adventure sports', 'Cultural immersion', 'Diverse landscapes', 'Comprehensive experience'], 'For adventure enthusiasts with good fitness levels and sporting experience.', '{"day1": "Leh arrival and acclimatization", "day2": "Local sightseeing and cycling", "day3": "River rafting on Indus", "day4": "Multi-day trek begins"}'::jsonb, 'Fly to Leh. Mandatory acclimatization period included in itinerary.', 'Multi-activity package. Equipment provided. Weather and water level dependent.', ARRAY['Sports clothing', 'Trekking boots', 'Sun protection', 'Personal gear', 'Adventure equipment provided']);

-- Insert sample vouchers for testing
INSERT INTO vouchers (user_id, code, discount_percentage, valid_until) VALUES
-- These will be updated with actual user IDs after users register
('00000000-0000-0000-0000-000000000000', 'WELCOME10', 10, '2024-12-31'),
('00000000-0000-0000-0000-000000000000', 'SUMMER20', 20, '2024-08-31');
